version: '3'
services:
  nginx:
    image: nginx:1.16.1-alpine
    container_name: node_nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  node_app:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/home/node/app
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "npm i && npm run start"
